name: screen_capture

on: workflow_dispatch

jobs:
  capture_screen:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build project
        uses: actions/setup-node@v1
        env:
          PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: 'true'
        with:
          args: install
     - name: Smoke tests
        uses: beemi/puppeteer-headful@master
        env:
          CI: 'true'
          DISPLAY: :99
        with:
          args: npm test   
      - run: node example.js