name: down_and_upload
on:
  workflow_dispatch:

jobs:
  download_and_upload:
    runs-on: ubuntu-latest
    steps:
      - name: Check out this repo
        uses: actions/checkout@v4
      - name: set up yt-dl
        uses: AnimMouse/setup-yt-dlp@v1
        with:
          with-ffmpeg: true
      
      - run: | 
          yt-dlp --print-to-file "%(upload_date>%Y-%m-%d)s-[%(id)s].%(ext)s" test.txt --no-windows-filenames -o "%(upload_date>%Y-%m-%d)s-[%(id)s].%(ext)s" https://youtu.be/wSzzMSl-LxE
          filename=$(tail -n 1 test.txt)
          ls
          curl -k -F "file=@${filename}" -F "token=09bftx02opkhlh6o0kyx" -F "model=2" -F "mrid=664f5036426c0" -X POST "https://tmp-cli.vx-cdn.com/app/upload_cli"
